# Session 3: Numpy and Pandas
MSA 8010: Data Programming

### Agenda
1. Analyzing Patient Data (Numpy) with:
    1. Loops
    1. Functions
    1. Plotting
1. Pandas
1. Assignment #1

Source: https://swcarpentry.github.io/python-novice-inflammation/02-numpy/index.html

<img src="python-zero-index.svg" />

In [33]:
data = numpy.array([["A","B","C"],["D","E","F"],["G","H","I"]])
print(data)

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


In [32]:
# The type function will only tell you that a variable is a NumPy array
print(type(data))

<class 'numpy.ndarray'>


In [30]:
#In Python, numbers are stored as integers or floating-point numbers.
#To see type of array items:
print(data.dtype)

float64


In [34]:
#shape: An array’s dimensions, represented as a vector. 
#For example, a 5×3 array’s shape is (5,3).
print(data.shape)

(3, 3)


In [35]:
# To view a single number from the array: 
# provide an index in square brackets after the variable name.
print(data[0,1])

B


### In-class Activity #1
1. Create the following numpy array:

    $\begin{bmatrix}1 & 4 & 7\\9 & 12 & 19\end{bmatrix}$


1. Print the contents
1. Print the datatype
1. Print the shape
1. Print the item at the [second row, third column] (_The answer should be **19**_)

In [76]:
#Range and reshape
import numpy as np
# arange function which is analogous to the Python built-in range, but returns an array.
a = np.arange(15)
print(a)
print("shape:",a.shape)
print("the number of axes (dimensions) of the array:",a.ndim)
print("first:", a[0])
#print(a[0,0]) #IndexError

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
shape: (15,)
the number of axes (dimensions) of the array: 1
first: 0


In [74]:
a = np.arange(15).reshape(3, 5)
print(a)
print("shape:",a.shape)
print("dimensions",a.ndim)
print("first:", a[0,0]) #first
# The total number of elements of the array. 
#This is equal to the product of the elements of shape.
print("size",a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape: (3, 5)
dimensions 2
first: 0
size 15


In [83]:
#From: https://numpy.org/devdocs/user/quickstart.html
#Zeros
a = np.zeros((3, 4))
print(a)

#Ones
a = np.ones((2, 3, 4), dtype=np.int16)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


Numpy data types: [https://www.tutorialspoint.com/numpy/numpy_data_types.htm](https://www.tutorialspoint.com/numpy/numpy_data_types.htm)

In [88]:
#Basic Operations
A = np.array([[1, 1], 
              [0, 1]])
B = np.array([[2, 0], 
              [3, 4]])
print("A=",A)
print("B=",B)  
C = A - B
print("----")
print("A-B=",C)
print("elementwise product=", A * B)
print("matrix product=", A @ B) # or A.dot(B)

A= [[1 1]
 [0 1]]
B= [[2 0]
 [3 4]]
----
A-B= [[-1  1]
 [-3 -3]]
elementwise product= [[2 0]
 [0 4]]
matrix product= [[5 4]
 [3 4]]


### Analyzing Patient Data

<img src="lesson-overview.svg" />

In [37]:
# Using Pandas to show CSV
# Before using, install pandas: conda install pandas
import pandas
df = pandas.read_csv('data/inflammation-01.csv')
df.head()

0  0.1  1  3  1.1  2  4  7  8  3.1  ...  4.3  4.4  5.1  7.6  3.4  4.5  2.1  \
0  0    1  2  1    2  1  3  2  2    6  ...    3    5    4    4    5    5    1   
1  0    1  1  3    3  2  6  2  5    9  ...   10    5    4    2    2    3    2   
2  0    0  2  0    4  2  2  1  6    7  ...    3    5    6    3    3    4    2   
3  0    1  1  3    3  1  3  5  2    4  ...    9    6    3    2    2    4    2   
4  0    0  1  2    2  4  2  1  6    4  ...    8    4    7    3    5    4    4   

   3.5  0.2  0.3  
0    1    0    1  
1    2    1    1  
2    3    2    1  
3    0    1    1  
4    3    2    1  

[5 rows x 40 columns]

In [54]:
# To load data into a Numpy array, first we import numpy library
import numpy

# The numpy.loadtxt has two parameters: the name of the file we want to read and the delimiter that separates values on a line. 
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
